name: Build Magic Lantern APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Fix Android Configuration and Subprojects
        run: |
          flutter clean
          flutter pub get
          cd android
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          cd ..

      - name: Build Android Release APK
        run: flutter build apk --release --target-platform android-arm64 --target=lib/main.dart

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
