name: Build Magic Lantern APK
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: magic_lantern
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --target-platform android-arm64

      - name: Upload APK Result
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: magic_lantern/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
